version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: sakamanish/ai-study-buddy-backend:latest
    env_file:
      - backend/.env
    ports:
      - "5000:5000"
    networks:
      - appnet

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: sakamanish/ai-study-buddy-frontend:latest
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
